Feat:написал проект
ODmain/java-filmorate pull request #5
Opened 2024-01-17 16:52 UTC by ODmain

2024-01-17 19:46 UTC, db-exp requested changes

2024-01-17 19:46 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty(message = "Имя не может быть пустым")
можно сразу и Size добавлять

2024-01-17 19:46 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Integer validName(User user) {
не, давай так не будем делать - лучше пока сделать так прям в методе
 if (validName(user) == 1) { ->  if (user.getName() == null || user.getName().isEmpty()) {
  } else if (validName(user) == 2) { -> } else if (user.getName().isBlank()) {
else {
 throw new ValidException("В имени присутствуют запрещённые символы", HttpStatus.BAD_REQUEST);
}

2024-01-17 19:46 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (validDate(film.getReleaseDate())) {
на всякий - на дату в модель Film можно повесить кастомный валидатор 
https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2024-01-17 19:50 UTC, ODmain commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (validDate(film.getReleaseDate())) {
ссылка не работает

2024-01-18 09:51 UTC, db-exp approved these changes

2024-02-19 11:16 UTC, merged